opinions_config:
  ignore_files:
    O002: ".*/models/staging/.*" # Ignore keyword requirement in staging
    O005: ".*/models/staging/.*" # Ignore primary key requirement in staging
  extra_opinions_config:
    O002_keywords:
      - summary
      - granularity
  custom_opinions:
    source: git
    repository: https://github.com/dbt-opiner/dbt-opiner-custom-opinions.git
